apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: watermark-engine
spec:
  template:
    spec:
      containers:
        - name: watermark-engine
          image: dev.local/watermark-engine
          imagePullPolicy: Never

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: watermark-engine
spec:
  filter:
    attributes:
      type: pending-watermark
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: watermark-engine
