apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuses
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: statuses
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: statuses
          image: dev.local/statuses
          imagePullPolicy: Never

---

  kind: Service
  apiVersion: v1
  metadata:
    name: statuses
  spec:
    type: NodePort
    selector:
      app: statuses
    ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
