apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: mongodb
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: IfNotPresent

---

# Service pointing at the previous Deployment. This will be the target for event
# consumption.
  kind: Service
  apiVersion: v1
  metadata:
    name: mongodb
  spec:
    selector:
      app: mongodb
    ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

