apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: status
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: status
          image: dev.local/status
          imagePullPolicy: Never

---

  kind: Service
  apiVersion: v1
  metadata:
    name: status
  spec:
    type: NodePort
    selector:
      app: status
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
